version: 2

updates:
- package-ecosystem: bundler
  directory: "/"
  labels:
    - "dependencies"
  schedule:
    interval: 'daily'
  open-pull-requests-limit: 10
  reviewers:
  - vaclavbohac
  target-branch: master
  versioning-strategy: lockfile-only
