version: '3.0'
services:
  redis:
    image: redis:5.0.0
    ports:
      - 6379:6379
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1

  db:
    build:
      context: ./postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    restart: always

volumes:
    db-data-volume:
