# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build-job:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.5.1-node
        environment:
          RAILS_ENV: test

    working_directory: /tmp/build

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: Yarn Install
          command: yarn install

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - persist_to_workspace:
          root: /tmp
          paths:
            - build

  test-job:
    docker:
      - image: circleci/ruby:2.5.1-node
        environment:
          DB_HOST: localhost
          DB_USERNAME: circleci-demo-go
          RAILS_ENV: test

      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: circleci-demo-go
          POSTGRES_DB: demagog_test

    working_directory: /tmp/build

    steps:
      - attach_workspace:
          at: ./

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      - run: bundle exec rake db:seed

      # Webpack setup
      - run: RAILS_ENV=test bundle exec bin/webpack

      # run rubocop
      - run:
          name: Run rubocop
          command: bundle exec rubocop

      # run eslint
      - run:
          name: Run eslint
          command: yarn lint

      - run:
          name: Run TypeScript compiler
          command: yarn run tsc --noEmit

      # run tests!
      - run:
          name: run tests
          command: |
            bundle exec rake test

      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

  deploy-job:
    docker:
      - image: circleci/ruby:2.5.1-node
        environment:
          RAILS_ENV: production

    working_directory: /tmp/build

    steps:
      - attach_workspace:
          at: ./

      - add_ssh_keys:
          fingerprints:
            - "58:90:71:2a:18:2d:40:bf:7e:bb:26:a5:3e:4d:d9:25"
      
      - run:
          name: Deploy to production
          command: bundle exec cap production deploy

workflows:
  version: 2
  build-test-hold-deploy:
    jobs:
      - build-job

      - test-job:
          requires:
            - build-job

      - hold:
          type: approval
          requires:
           - test-job

      - deploy-job:
          requires:
            - hold
