# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1

orbs:
  ruby: circleci/ruby@1.1.0
  node: circleci/node@2

jobs:
  build-job:
    docker:
      # specify the version you desire here
      - image: cimg/ruby:3.1.4-node
        environment:
          RAILS_ENV: test

    steps:
      - checkout
      - run:
            name: "Update Node.js"
            command: |
              curl -sSL "https://nodejs.org/dist/v16.16.0/node-v16.16.0-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v16.16.0-linux-x64/bin/node
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"

  test-job:
    docker:
      - image: cimg/ruby:3.1.4-node
        environment:
          DB_HOST: localhost
          DB_USERNAME: circleci-demo-go
          RAILS_ENV: test

      - image: cimg/postgres:9.6
        environment:
          POSTGRES_USER: circleci-demo-go
          POSTGRES_DB: demagog_test

      - image: elasticsearch:7.3.0
        environment:
          - discovery.type=single-node
          - bootstrap.memory_lock=true

    steps:
      - checkout
      - run:
          name: "Update Node.js"
          command: |
            curl -sSL "https://nodejs.org/dist/v16.16.0/node-v16.16.0-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v16.16.0-linux-x64/bin/node
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Database setup
      - run: bundle exec rails db:create
      - run: bundle exec rails db:schema:load
      - run: bundle exec rails db:seed

      # Webpack setup
      - run: RAILS_ENV=test bin/webpack

      - run: bundle exec rails test
      - ruby/rubocop-check

      # run eslint
      - run:
          name: Run eslint
          command: yarn lint

      - run:
          name: Run TypeScript compiler
          command: yarn run tsc --noEmit

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-job

      - test-job:
          requires:
            - build-job
