local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

amazon:
  service: S3
  access_key_id: <%= ENV["AMAZON_S3_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["AMAZON_S3_SECRET_ACCESS_KEY"] %>
  region: <%= ENV["AMAZON_S3_REGION"] %>
  bucket: <%= ENV["AMAZON_S3_BUCKET"] %>
  endpoint: <%= ENV["AMAZON_S3_ENDPOINT"] %>
